### ISSUE TITLE
Colon placement w.r.t. bold

### ISSUE THREAD

**Issue by ReedCopsey** [Microsoft/visualfsharpdocs#122]
As noted by @Vandroiy here: https://github.com/Microsoft/visualfsharpdocs/pull/121#discussion_r64967978 

The conversion tooling placed colons _inside_ of the bold, and technically it should be outside. I recommended he not change it in his PR (to match the majority of the docs).

However, I would be willing to modify my previous scripts to fix this across the repository.  Would it be better to follow the Chicago Manual of Style recommendations that punctuation "should appear in the same font (...) as the enclosing text"?

**Comment by Vandroiy** [comment]
Actually... I'm not even sure I'm reading the recommendation right and changed my PR already.

[Here's a StackExchange question on this](http://writers.stackexchange.com/questions/14157/do-you-bold-punctuation-directly-after-bold-text), and there's an exception "for punctuation that belongs to a title"

I only did this because I didn't look at enough files to see that the one with non-bold colons was a rare one-off. The rest of the MSDN seems to use bold colons too.

This is just drawing attention away from useful changes and I can't even make out which way would be "right". I think it can be left alone.

**Comment by ReedCopsey** [comment]
@Vandroiy Reading that SO question would suggest the current version is correct, since these are effectively "titles".  Going to close this.

**Comment by Vandroiy** [comment]
Thanks and sorry about this, it was sloppy editing on my part. (I also did this in the formatting edits on my previous PR on map addition; I'll revert that too.)
