### ISSUE TITLE
Snippets have large empty space at the top

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharpdocs#36]
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/async.awaitevent['del,'t]-method-[fsharp]

![image](https://cloud.githubusercontent.com/assets/873919/15333053/b3dbf402-1c70-11e6-84b9-8c86f0863e9d.png)

**Comment by dend** [comment]
Assigning to myself. This is something I need to fix across the entire stack.

**Comment by smoothdeveloper** [comment]
Should it be "quickfixed" first with a pass replacing all "more than 3 consecutive empty lines" with "2 consecutive empty lines" across the repository, and later taken care in a more fine-grained manner?

**Comment by ReedCopsey** [comment]
@dend and @smoothdeveloper I have an idea (after my last round of edits, thought of something) - going to try something with this...

**Comment by dend** [comment]
@ReedCopsey let me know where you land with with, I might just write a C#/Python script to do a run-through and fix the formatting.

**Comment by ReedCopsey** [comment]
@dend Done - PR coming shortly.  It's a big one, though.

**Comment by ReedCopsey** [comment]
@dend FYI: This took a bit longer because I kept running across edge cases.  My "rule" here was to process all files looking for pairs of triple back ticks, and removing all but one blank line above the first, and all blank lines after, and all blank lines before the 2nd, and all but one after.  This takes it down but still leaves a blank line before and after each code sample (and none inside, other than any inside the code itself).

I've checked about a hundred of the files changed -so far, all look perfect.

**Comment by ReedCopsey** [comment]
@vasily-kirichenko and @dend I believe this can be closed now.

**Comment by smoothdeveloper** [comment]
I know it is merged, but I'm still reviewing...

**Comment by dend** [comment]
Closing this for now. If there are any articles that have this issue, feel free to re-open an issue with the specific article mentioned.
